<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>TaskJuggler</string>
    <key>scopeName</key>
    <string>source.tjp3</string>
    <key>fileTypes</key>
    <array>
      <string>tjp3</string>
    </array>
    <key>uuid</key>
    <string>24341012-fbff-4468-926e-348ed6563de2</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#account</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#leaves</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#shift</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#vacation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>account</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(account)\b\s*(?:((?:\b[a-zA-Z_][a-zA-Z0-9_]*\b))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))\s*\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.account.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.account.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#account-inclusions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(account)\b\s*(?:((?:\b[a-zA-Z_][a-zA-Z0-9_]*\b))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.account.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.account.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>account-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#flags</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#credits</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#aggregate</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#account</string>
          </dict>
        </array>
      </dict>
      <key>aggregate</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>^\s*(aggregate)\s*(resources|tasks)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.aggregate.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.other.aggregate.tjp3</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>credits</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(credits)\b</string>
            <key>end</key>
            <string>(?:(?&lt;![,\s])\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.credits.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#credits-inclusions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>credits-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#date</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
        </array>
      </dict>
      <key>date</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.date.tjp3</string>
            <key>match</key>
            <string>(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\}))</string>
          </dict>
        </array>
      </dict>
      <key>flags</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(flags)\b</string>
            <key>end</key>
            <string>(?:(?&lt;![,\s])\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.flags.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literals</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.type.flags.tjp3</string>
                <key>match</key>
                <string>(?:\b[a-zA-Z_][a-zA-Z0-9_]*\b)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>leaves</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(leaves)\b</string>
            <key>end</key>
            <string>(?:(?&lt;![,\s])\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.leaves.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#leaves-inclusions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>leaves-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:project|annual|special|sick|unpaid|holiday|unemployed)</string>
            <key>name</key>
            <string>constant.language.leaves.tjp3</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\b[a-zA-Z_][a-zA-Z0-9_]*\b)</string>
            <key>name</key>
            <string>entity.name.type.leaves.tjp3</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:(?:(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\}))\s*(?:\-\s*(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\}))|(?:\+\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))))|(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\})))</string>
            <key>name</key>
            <string>constant.numeric.interval.tjp3</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#date</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.tjp3</string>
            <key>match</key>
            <string>(?:(?:\d+\.\d+)|(?:\d+))</string>
          </dict>
        </array>
      </dict>
      <key>replace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>replace</string>
            <key>name</key>
            <string>storage.type.replace.tjp3</string>
          </dict>
        </array>
      </dict>
      <key>shift</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(shift)\b\s*(?:((?:\b[a-zA-Z_][a-zA-Z0-9_]*\b))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))\s*\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.shift.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.shift.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#shift-inclusions</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(shift)\b\s*(?:((?:\b[a-zA-Z_][a-zA-Z0-9_]*\b))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.shift.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.shift.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>shift-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#leaves</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#replace</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#shift</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#timezone</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#vacation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#workinghours</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.tjp3</string>
            <key>match</key>
            <string>(?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\')</string>
          </dict>
        </array>
      </dict>
      <key>timezone</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(timezone)\s*(?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\')</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.timezone.tjp3</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>vacation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(vacation)\b</string>
            <key>end</key>
            <string>(?:(?&lt;![,\s])\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.vacation.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#vacation-inclusions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>vacation-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:\b[a-zA-Z_][a-zA-Z0-9_]*\b)</string>
            <key>name</key>
            <string>entity.name.type.vacation.tjp3</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:(?:(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\}))\s*(?:\-\s*(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\}))|(?:\+\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))))|(?:(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)|(?:%\s*\{\s*(?:\d\d\d\d-\d\d-\d\d(?:-\d\d:\d\d(?::\d\d)?)?(?:-[+-]\d\d\d\d)?)\s*(?:[+-]\s*(?:(?:\d+\.\d+)|(?:\d+))\s*(?:min|h|d|w|m|y))\s*\})))</string>
            <key>name</key>
            <string>constant.numeric.interval.tjp3</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
        </array>
      </dict>
      <key>workinghours</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(workinghours)\b</string>
            <key>end</key>
            <string>(?:(?&lt;![,\s])\s*$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.workinghours.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#workinghours-inclusions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>workinghours-inclusions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>off</string>
            <key>name</key>
            <string>constant.language.workinghours.tjp3</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:sun|mon|tue|wed|thu|fri|sat)</string>
            <key>name</key>
            <string>constant.numeric.weekday.tjp3</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\d\d?:\d\d(?::\d\d)?)</string>
            <key>name</key>
            <string>constant.numeric.time.tjp3</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>