<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>TaskJuggler</string>
    <key>scopeName</key>
    <string>source.tjp3</string>
    <key>fileTypes</key>
    <array>
      <string>tjp3</string>
    </array>
    <key>uuid</key>
    <string>24341012-fbff-4468-926e-348ed6563de2</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#account</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>account</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\s*(account)\s+(?:((?:[a-zA-Z_][a-zA-Z0-9_]*))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))\s*\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.account.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.account.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>^\s*(flags)\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.flags.tjp3</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>begin</key>
                <string>^\s*(flags)\s</string>
                <key>end</key>
                <string>((?:[a-zA-Z_][a-zA-Z0-9_]*))\s*$</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.type.flags.tjp3</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.flags.tjp3</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>((?:[a-zA-Z_][a-zA-Z0-9_]*))</string>
                    <key>captures</key>
                    <dict>
                      <key>1</key>
                      <dict>
                        <key>name</key>
                        <string>entity.name.type.flags.tjp3</string>
                      </dict>
                    </dict>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>^\s*(account)\s+(?:((?:[a-zA-Z_][a-zA-Z0-9_]*))\s+)?((?:\"(?:[^\"\\]|\\.)+\"|\'(?:[^\'\\]|\\.)+\'))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.account.tjp3</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.account.tjp3</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.tjp3</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>